### ISSUE TITLE
建议使用一种更容易理解和的语法，如下

### ISSUE THREAD

**Issue by zswang** [techird/ruler#1]
# 尺规作图，语法设计

标签： 尺规作图 语法

---
## 思路

主要依赖类型推断，比如 point 和 point 组成 line，point 和 number 组成圆弧
## 运算符
- 赋值 `=`
- 组合 `,`
- 求相交 `*`
- 求距离 `~`
- 括号 `(` 表达式 `)`
- 选择 `[index]`
### 赋值

标识符 = 表达式

赋值时可以省略括号
### define point

语法 `(` number `,` number `)`

(eg)

```
A=0,0
B=0,2
C=100,222
```
### define distance

语法 `(` point `~` point `)`

(eg)

```
ab=A~B
bc=B~C
```
### define line

语法 `(` point `~` point `)`

(eg)

```
AB=A,B
BC=B,C
```
### define arc

语法 `(` point `,` distance `)`

(eg)

```
A1=A,100
A2=A,ab
```
### define intersect line & line

语法 `(` line `*` line `)`

(eg)

```
X1=AB*BC
X2=AB*((1,1),(2,1))
```
### define intersect arc & line

语法 `(` arc `*` line `)` | `(` line `*` arc `)`

(eg)

```
X1=C1*BC
X2=C1*((1,1),(2,1))
```
### define intersect arc & arc

语法 `(` arc `*` arc `)`

(eg)

```
X1=C1*C2
X2=C1*((1,1),((2,1)~A1))
```

**Comment by zswang** [comment]
A=0,0 #color: red // 配置样式

**Comment by techird** [comment]
精彩，语法复杂度瞬间降低，学习成本很低了。

另外，样式可以独立出来，写样式表那样的形式：

``` css
A, B { fill: red; size: 5; stroke: blue; stroke-width: 12; }
```

**Comment by zswang** [comment]
直线和圆弧相交
圆弧和圆弧相交

有两个点
可以作为直线返回

直线可以取下标
`AB[0]` 端点1 `AB[1]` 端点2

**Comment by techird** [comment]
我觉得可以返回一个叫 `Point[]` 类型的点数组，用作直线有歧义。可以再加一个 `select` 类型的步骤，选择具体的点。比如：

``` js
var a1 = ruler.step('define_arc', [p1, d1]);
var a2 = ruler.step('define_arc', [p2, d2]);
var aa = ruler.step('intersect_arc_arc', [a1, a2]);
var i1 = ruler.step('select', aa, 0);
```
